version: "3"

services:
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql

  myadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT= "100G"
    ports:
      - 8080:80

  docker-hoster:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

volumes:
  mariadb:
